---
- name: Tomcat. Install need packages
  yum:
    update_cache: yes
    name: "{{ yum_tomcat_packages }}"
    state: latest

- name: Tomcat. Install tomcat
  include: install_tomcat_Centos.yaml

- name: Mysql. Install
  include: install_mysql.yaml

- name: Xwiki. Install
  include: install_xwiki.yaml
